import assert from "node:assert/strict";
import { afterEach, test } from "node:test";
import { JSDOM } from "jsdom";
const dom = new JSDOM("<!doctype html><html><body></body></html>", { url: "http://localhost/calculators/vehicle-acquisition-tax/" });
Object.defineProperties(globalThis, { window:{value:dom.window,configurable:true},document:{value:dom.window.document,configurable:true},navigator:{value:dom.window.navigator,configurable:true},HTMLElement:{value:dom.window.HTMLElement,configurable:true},HTMLInputElement:{value:dom.window.HTMLInputElement,configurable:true},Node:{value:dom.window.Node,configurable:true},DOMException:{value:dom.window.DOMException,configurable:true},getComputedStyle:{value:dom.window.getComputedStyle.bind(dom.window),configurable:true},IS_REACT_ACT_ENVIRONMENT:{value:true,configurable:true,writable:true} });
const { cleanup, render, screen } = await import("@testing-library/react"); const userEvent = (await import("@testing-library/user-event")).default; const { VehicleAcquisitionTaxCalculator } = await import("../components/calculators/VehicleAcquisitionTaxCalculator.tsx"); const React = await import("react");
afterEach(cleanup); function mount(){render(React.createElement(VehicleAcquisitionTaxCalculator));} async function replace(user,label,value){const input=screen.getByLabelText(label);await user.clear(input);await user.type(input,value);}
test("일반 승용 신차와 전기차 감면 결과를 보여주고 초기화한다", async()=>{const user=userEvent.setup();mount();await replace(user,"취득세 과세표준액","30000000");await user.click(screen.getByRole("button",{name:"예상 취득세 계산"}));assert.ok(screen.getAllByText("2,100,000원").length>=2);await user.selectOptions(screen.getByLabelText("친환경 유형"),"electric");await user.click(screen.getByRole("button",{name:"예상 취득세 계산"}));assert.ok(screen.getByText("700,000원"));assert.ok(screen.getByText("전기자동차 감면"));await user.click(screen.getByRole("button",{name:"초기화"}));assert.equal(screen.getByLabelText("취득세 과세표준액").value,"");});
test("중고차 과세표준과 차량 유형 전환을 반영한다", async()=>{const user=userEvent.setup();mount();await user.selectOptions(screen.getByLabelText("취득 방식"),"used");await replace(user,"실제 취득가격","12000000");await replace(user,"차량 시가표준액","14000000");await user.click(screen.getByRole("button",{name:"예상 취득세 계산"}));assert.ok(screen.getAllByText("14,000,000원").length>=2);assert.ok(screen.getAllByText("980,000원").length>=2);await user.selectOptions(screen.getByLabelText("차량 유형"),"lightPassenger");await user.click(screen.getByRole("button",{name:"예상 취득세 계산"}));assert.ok(screen.getByText("0원"));assert.ok(screen.getByText("경형 승용자동차 감면"));});
test("필수 금액 오류를 표시한다", async()=>{const user=userEvent.setup();mount();await user.click(screen.getByRole("button",{name:"예상 취득세 계산"}));assert.ok(screen.getByRole("alert"));});
