export const PUBLIC_CALCULATOR_SEO = {
  "seller-margin": {
    slug: "seller-margin",
    path: "/calculators/seller-margin/",
    title: "판매자 마진 계산기 | 수수료·원가·순이익 계산",
    description:
      "판매단가, 수량, 개당 원가, 할인, 배송비, 플랫폼·결제 수수료와 광고비를 입력해 예상 정산금액과 세전 순이익을 계산합니다.",
    image: "https://gyesanbox.kr/og/seller-margin.png",
    imagePath: "/og/seller-margin.png",
    imageAlt: "판매자 마진 계산기 — 판매가·원가·수수료 기준 순이익 확인",
    representativeTerm: "판매자 마진 계산기",
    supportingTerms: ["판매가", "원가", "플랫폼 수수료", "순이익"],
    questionTerms: ["판매 수수료를 빼면 얼마가 남는지", "마진율 계산"],
    purposeTerms: ["온라인 판매 정산", "주문별 수익 확인"],
    conditionTerms: ["판매단가", "수량", "배송비", "광고비"],
  },
  salary: {
    slug: "salary",
    path: "/calculators/salary/",
    title: "2026 연봉 실수령액 계산기 | 월급·4대보험·소득세 계산",
    description:
      "연봉과 비과세액, 공제대상 가족 수를 입력해 2026년 국민연금·건강보험·고용보험·소득세를 반영한 월급 실수령액을 계산합니다.",
    image: "https://gyesanbox.kr/og/salary.png",
    imagePath: "/og/salary.png",
    imageAlt: "연봉 실수령액 계산기 — 월급과 공제 후 금액 확인",
    representativeTerm: "연봉 실수령액 계산기",
    supportingTerms: ["월급", "4대보험", "소득세", "공제액"],
    questionTerms: ["연봉에서 실제로 받는 월급", "공제 후 실수령액"],
    purposeTerms: ["급여 예상", "연봉 비교"],
    conditionTerms: ["비과세액", "공제대상 가족 수"],
  },
  loan: {
    slug: "loan",
    path: "/calculators/loan/",
    title: "대출 이자 계산기 | 원리금균등·원금균등·만기일시상환 비교",
    description:
      "대출금액과 연이율, 기간을 입력해 월 납입액과 총이자를 계산하고 원리금균등·원금균등·만기일시상환 결과와 월별 일정을 비교해 보세요.",
    image: "https://gyesanbox.kr/og/loan.png",
    imagePath: "/og/loan.png",
    imageAlt: "대출 이자 계산기 — 상환 방식별 월 납입액과 총이자 비교",
    representativeTerm: "대출 이자 계산기",
    supportingTerms: ["원리금균등", "원금균등", "만기일시상환", "총이자"],
    questionTerms: ["대출 월 납입액", "상환 방식별 이자"],
    purposeTerms: ["대출 상환 비교", "월별 일정 확인"],
    conditionTerms: ["대출금액", "연이율", "기간"],
  },
  severance: {
    slug: "severance",
    path: "/calculators/severance/",
    title: "퇴직금 계산기 | 평균임금·통상임금 기준 예상 퇴직금 계산",
    description:
      "입사일, 퇴직일, 퇴직 전 3개월 임금과 상여금·연차수당을 입력해 평균임금·통상임금 기준 예상 퇴직금을 계산합니다.",
    image: "https://gyesanbox.kr/og/severance.png",
    imagePath: "/og/severance.png",
    imageAlt: "퇴직금 계산기 — 평균임금과 통상임금 기준 예상 퇴직금 계산",
    representativeTerm: "퇴직금 계산기",
    supportingTerms: ["평균임금", "통상임금", "퇴직 전 3개월", "예상 퇴직금"],
    questionTerms: ["퇴직하면 받을 금액", "퇴직금 산정"],
    purposeTerms: ["퇴직 전 예상", "임금 기준 확인"],
    conditionTerms: ["입사일", "퇴직일", "상여금", "연차수당"],
  },
  unemployment: {
    slug: "unemployment",
    path: "/calculators/unemployment/",
    title: "실업급여 계산기 2026 | 구직급여 상한액·하한액·수급기간 예상",
    description:
      "실업급여 계산기로 퇴직 전 임금 기준 1일 구직급여액, 상한액·하한액 적용 여부, 고용보험 가입기간별 수급기간과 예상 총액을 확인하세요. 실제 지급 여부는 퇴직 사유, 이직확인서, 실업인정 절차에 따라 달라질 수 있습니다.",
    image: "https://gyesanbox.kr/og/unemployment.png",
    imagePath: "/og/unemployment.png",
    imageAlt: "실업급여 계산기 — 구직급여 예상 금액과 수급기간 확인",
    representativeTerm: "실업급여 계산기",
    supportingTerms: ["구직급여", "상한액", "하한액", "수급기간"],
    questionTerms: ["실업급여 예상 금액", "몇 일 동안 받을 수 있는지"],
    purposeTerms: ["퇴직 후 급여 예상", "고용보험 가입기간 확인"],
    conditionTerms: ["퇴직 전 임금", "고용보험 가입기간", "퇴직 사유"],
  },
  "social-insurance": {
    slug: "social-insurance",
    path: "/calculators/social-insurance/",
    title: "4대보험 계산기 2026 | 국민연금·건강보험 공제액 계산",
    description:
      "2026년 기준 국민연금, 건강보험, 장기요양보험, 고용보험 근로자 부담 공제액을 월급과 비과세 금액으로 계산합니다.",
    image: "https://gyesanbox.kr/og/social-insurance-hero.png",
    imagePath: "/og/social-insurance-hero.png",
    imageAlt: "4대보험 계산기 — 국민연금·건강보험·고용보험 공제액 계산",
    representativeTerm: "4대보험 계산기",
    supportingTerms: ["국민연금", "건강보험", "장기요양보험", "고용보험"],
    questionTerms: ["월급에서 4대보험 공제액", "근로자 부담 보험료"],
    purposeTerms: ["급여 공제 확인", "보험별 부담액 비교"],
    conditionTerms: ["월 급여", "비과세 금액"],
  },
  "labor-pay": {
    slug: "labor-pay",
    path: "/calculators/labor-pay/",
    title: "주휴수당 계산기 2026 | 알바 주휴수당과 주급 계산",
    description:
      "2026년 최저임금과 근로기준법 기준을 참고해 시급제·단시간 근로자의 예상 주휴시간, 주휴수당, 주휴 포함 주급을 계산합니다.",
    image: "https://gyesanbox.kr/og/labor-pay-hero.png",
    imagePath: "/og/labor-pay-hero.png",
    imageAlt: "주휴수당 계산기 — 시급과 근로시간 기준 주급 계산",
    representativeTerm: "주휴수당 계산기",
    supportingTerms: ["알바 주휴수당", "주휴시간", "주급", "시급"],
    questionTerms: ["주휴수당이 얼마인지", "주휴 포함 주급"],
    purposeTerms: ["시급제 급여 예상", "근로시간별 계산"],
    conditionTerms: ["근무시간", "시급", "개근 여부"],
  },
  "vat-profit": {
    slug: "vat-profit",
    path: "/calculators/vat-profit/",
    title: "부가세 계산기 | 공급가액·합계금액 부가가치세 계산",
    description:
      "공급가액 또는 부가세 포함 합계금액을 입력해 매출세액, 합계금액, 매입세액 차감 후 예상 납부세액을 계산합니다.",
    image: "https://gyesanbox.kr/og/vat-profit-hero.png",
    imagePath: "/og/vat-profit-hero.png",
    imageAlt: "부가세 계산기 — 공급가액과 합계금액 기준 부가가치세 계산",
    representativeTerm: "부가세 계산기",
    supportingTerms: ["부가가치세", "공급가액", "합계금액", "매입세액"],
    questionTerms: ["부가세 포함 가격", "예상 납부세액"],
    purposeTerms: ["매출세액 계산", "사업자 금액 확인"],
    conditionTerms: ["공급가액", "부가세 포함 합계금액", "매입세액"],
  },
  "parental-leave": {
    slug: "parental-leave",
    path: "/calculators/parental-leave/",
    title: "육아휴직급여 계산기 | 월 통상임금 기준 예상 급여 계산",
    description:
      "월 통상임금과 육아휴직 사용 개월 수로 일반 육아휴직급여의 월별 예상액, 총 예상 수령액, 상한·하한 적용 여부를 계산합니다.",
    image: "https://gyesanbox.kr/og/parental-leave-hero.png",
    imagePath: "/og/parental-leave-hero.png",
    imageAlt: "육아휴직급여 계산기 — 월 통상임금 기준 예상 급여 계산",
    representativeTerm: "육아휴직급여 계산기",
    supportingTerms: ["통상임금", "월별 예상액", "상한액", "하한액"],
    questionTerms: ["육아휴직 중 받을 급여", "총 예상 수령액"],
    purposeTerms: ["휴직 기간 급여 예상", "월별 지급액 확인"],
    conditionTerms: ["월 통상임금", "사용 개월 수"],
  },
  "rent-vs-jeonse": {
    slug: "rent-vs-jeonse",
    path: "/calculators/rent-vs-jeonse/",
    title: "전세 vs 월세 비교 계산기 | 전세대출 이자·월세 부담 비교",
    description:
      "전세대출 이자, 월세, 관리비, 보증금 기회비용을 입력해 전세와 월세의 월 부담과 거주기간 총비용을 비교해 보세요.",
    image: "https://gyesanbox.kr/og/rent-vs-jeonse-hero.png",
    imagePath: "/og/rent-vs-jeonse-hero.png",
    imageAlt: "전세 vs 월세 비교 계산기 — 보증금과 월세 부담 비교",
    representativeTerm: "전세 vs 월세 비교 계산기",
    supportingTerms: ["전세대출 이자", "월세", "관리비", "기회비용"],
    questionTerms: ["전세와 월세 중 부담이 적은지", "거주기간 총비용"],
    purposeTerms: ["주거비 비교", "계약 조건별 비용 확인"],
    conditionTerms: ["보증금", "월세", "관리비", "거주기간"],
  },
} as const;

export type PublicCalculatorSlug = keyof typeof PUBLIC_CALCULATOR_SEO;

export const PUBLIC_CALCULATOR_SEO_SOURCE_NOTE =
  "GSC 자료 미제공; 페이지 기능·공식 용어·사용자 질문형 의도에 근거한 후보 키워드입니다.";
