export type CalculatorCategory = "급여" | "금융" | "주거" | "사업" | "투자" | "생활";
export type CalculatorValueGrade = "A" | "B" | "C";

export type CalculatorRegistryItem = {
  id: string;
  path: `/calculators/${string}/`;
  title: string;
  category: CalculatorCategory;
  description: string;
  inputOutput?: string;
  searchAliases: readonly string[];
  searchIntents: readonly string[];
  valueGrade: CalculatorValueGrade;
  flagship?: true;
};

export const CALCULATOR_REGISTRY = [
  {
    id: "loan",
    path: "/calculators/loan/",
    title: "대출 이자 계산기",
    category: "금융",
    description: "원리금균등·원금균등·만기일시상환의 이자와 월별 일정을 비교합니다.",
    inputOutput: "대출금액, 연이율, 기간 → 월 납입액, 총이자, 상환 일정",
    searchAliases: ["원리금 계산기", "대출 상환", "대출이자", "월 상환액"],
    searchIntents: ["대출 이자가 얼마인지", "상환 방식 비교", "매달 얼마를 갚는지"],
    valueGrade: "A",
    flagship: true,
  },
  {
    id: "rent-vs-jeonse",
    path: "/calculators/rent-vs-jeonse/",
    title: "전세 vs 월세 비교 계산기",
    category: "주거",
    description: "전세대출 이자와 보증금 기회비용, 월세·관리비를 함께 비교합니다.",
    inputOutput: "보증금, 대출금리, 월세, 관리비, 거주기간 → 월 부담, 총비용, 조건부 비교",
    searchAliases: ["전월세", "월세 비교", "전세 계산기", "주거비"],
    searchIntents: ["전세와 월세 중 무엇이 유리한지", "이사 전 주거비 비교"],
    valueGrade: "A",
  },
  {
    id: "salary",
    path: "/calculators/salary/",
    title: "연봉 실수령액 계산기",
    category: "급여",
    description: "2026년 기준 4대보험과 간이세액표를 적용한 예상 실수령액을 확인합니다.",
    inputOutput: "연봉, 월 비과세액, 가족 수 → 월 실수령액, 공제 항목별 금액",
    searchAliases: ["월급", "실수령액", "세후 월급", "연봉 계산기"],
    searchIntents: ["연봉에서 실제로 받는 돈", "월급 공제 후 금액", "세전 세후 비교"],
    valueGrade: "A",
    flagship: true,
  },
  {
    id: "social-insurance",
    path: "/calculators/social-insurance/",
    title: "4대보험 계산기",
    category: "급여",
    description: "월 급여와 비과세 금액으로 국민연금·건강보험·장기요양보험·고용보험의 근로자 부담액을 계산합니다.",
    inputOutput: "월 급여, 비과세 금액 → 보험별 공제액, 총 공제액, 공제 후 참고 금액",
    searchAliases: ["보험", "보험료", "사대보험", "국민연금", "건강보험"],
    searchIntents: ["월급에서 보험료가 얼마나 빠지는지", "근로자 보험 부담액"],
    valueGrade: "A",
    flagship: true,
  },
  {
    id: "seller-margin",
    path: "/calculators/seller-margin/",
    title: "판매자 마진 계산기",
    category: "사업",
    description: "판매 비용을 바탕으로 정산금액, 순이익과 순이익률을 확인합니다.",
    inputOutput: "판매가, 수량, 원가, 수수료, 배송비 → 정산금액, 순이익, 순이익률",
    searchAliases: ["마진", "판매 수익", "스마트스토어 마진", "정산금액"],
    searchIntents: ["판매하고 얼마가 남는지", "수수료를 뺀 순이익"],
    valueGrade: "A",
  },
  {
    id: "vat-profit",
    path: "/calculators/vat-profit/",
    title: "부가세 계산기",
    category: "사업",
    description: "공급가액 또는 합계금액으로 매출세액과 예상 납부세액을 계산합니다.",
    inputOutput: "매출 금액, 입력 기준, 매입세액 → 공급가액, 매출세액, 예상 납부세액",
    searchAliases: ["부가가치세", "VAT", "공급가액", "세금계산서"],
    searchIntents: ["부가세 포함 가격", "매입세액을 뺀 예상 세액"],
    valueGrade: "B",
  },
  {
    id: "labor-pay",
    path: "/calculators/labor-pay/",
    title: "주휴수당 계산기",
    category: "급여",
    description: "시급과 소정근로시간, 실제 근로시간, 개근 여부로 예상 주휴수당을 계산합니다.",
    inputOutput: "시급, 주 소정근로시간, 실제 근로시간, 개근 여부 → 주휴시간, 주휴수당, 주급",
    searchAliases: ["알바", "주급", "시급", "주휴"],
    searchIntents: ["알바 주휴수당", "주 15시간 수당", "시급으로 주급 계산"],
    valueGrade: "A",
  },
  {
    id: "severance",
    path: "/calculators/severance/",
    title: "퇴직금 계산기",
    category: "급여",
    description: "입사일과 퇴직 전 임금을 바탕으로 법정 퇴직금 예상액과 대상 여부를 확인합니다.",
    inputOutput: "입사일, 퇴직일, 임금총액, 상여금 → 평균임금, 예상 퇴직금",
    searchAliases: ["퇴사", "퇴직", "퇴직급여", "평균임금"],
    searchIntents: ["퇴사하면 받을 돈", "1년 근무 퇴직금", "퇴직 전 임금 기준"],
    valueGrade: "A",
    flagship: true,
  },
  {
    id: "unemployment",
    path: "/calculators/unemployment/",
    title: "실업급여 계산기",
    category: "급여",
    description: "임금과 고용보험 가입기간으로 1일 구직급여액, 지급일수와 예상 총액을 계산합니다.",
    inputOutput: "임금, 가입기간, 나이 구간, 퇴직 사유 → 1일 급여액, 지급일수, 총액",
    searchAliases: ["퇴사", "구직급여", "고용보험", "실업 수당"],
    searchIntents: ["퇴사 후 받을 수 있는 돈", "실업급여 기간", "계약만료 실업급여"],
    valueGrade: "A",
    flagship: true,
  },
  {
    id: "parental-leave",
    path: "/calculators/parental-leave/",
    title: "육아휴직급여 계산기",
    category: "급여",
    description: "월 통상임금과 휴직 기간, 특례 조건으로 월별 예상 급여와 총액을 계산합니다.",
    inputOutput: "월 통상임금, 사용 개월 수, 특례 조건 → 월별 예상액, 상·하한 적용, 총 예상액",
    searchAliases: ["육아휴직", "육휴", "육아 급여", "통상임금"],
    searchIntents: ["육아휴직 중 받을 돈", "육아휴직 월별 급여"],
    valueGrade: "A",
  },
  {
    id: "roas",
    path: "/calculators/roas/",
    title: "ROAS 계산기",
    category: "사업",
    description: "광고비 대비 매출과 광고 후 순이익, 손익분기 ROAS를 비교합니다.",
    searchAliases: ["광고 수익률", "광고비", "로아스", "손익분기 ROAS"],
    searchIntents: ["광고비 대비 매출", "광고가 이익인지"],
    valueGrade: "B",
  },
  {
    id: "savings",
    path: "/calculators/savings/",
    title: "예금·적금 계산기",
    category: "금융",
    description: "금리와 과세 방식에 따른 세전 이자, 세금과 만기 예상액을 계산합니다.",
    searchAliases: ["적금", "적금 이자", "예금 이자", "만기 수령액"],
    searchIntents: ["적금 만기에 받는 돈", "세후 예금 이자", "저축 이자 계산"],
    valueGrade: "A",
    flagship: true,
  },
  {
    id: "average-price",
    path: "/calculators/average-price/",
    title: "물타기 계산기",
    category: "투자",
    description: "추가매수 전후의 평균단가·투입원금 변화와 두 시나리오를 중립적으로 비교합니다.",
    inputOutput: "보유 수량·평단, 추가매수 조건, 선택 현재가 → 전후 원금·평단 변화율, 시나리오 비교",
    searchAliases: ["평단가", "평균단가", "평균 매수가", "추가 매수", "주식 물타기"],
    searchIntents: ["추가 매수하면 평단이 얼마인지", "추가매수 조건 비교", "현재가에서 평단까지 변화율"],
    valueGrade: "A",
  },
  {
    id: "card-installment",
    path: "/calculators/card-installment/",
    title: "카드 할부 계산기",
    category: "금융",
    description: "할부 월 납입액과 총 수수료, 회차별 원금·수수료를 계산합니다.",
    searchAliases: ["할부", "카드 수수료", "무이자 할부", "월 납입액"],
    searchIntents: ["카드로 나눠 내면 얼마인지", "할부 수수료"],
    valueGrade: "B",
  },
  {
    id: "brokerage-fee",
    path: "/calculators/brokerage-fee/",
    title: "부동산 중개보수 계산기",
    category: "주거",
    description: "거래 유형과 금액별 중개보수 상한과 협의보수를 계산합니다.",
    searchAliases: ["복비", "중개수수료", "부동산 수수료", "월세 복비"],
    searchIntents: ["전세 중개수수료", "집 계약 복비", "매매 중개보수"],
    valueGrade: "A",
  },
  {
    id: "car-cost",
    path: "/calculators/car-cost/",
    title: "자동차 유지비 계산기",
    category: "생활",
    description: "연료비·보험료·세금 등 월·연간 차량 비용과 1km당 비용을 계산합니다.",
    searchAliases: ["차 유지비", "차량 유지비", "기름값", "자동차 비용"],
    searchIntents: ["차를 보유하면 매달 얼마인지", "연간 차량 비용"],
    valueGrade: "B",
  },
  {
    id: "overtime-pay",
    path: "/calculators/overtime-pay/",
    title: "연장·야간·휴일근로수당 계산기",
    category: "급여",
    description: "근로기준법 가산율에 따른 연장·야간·휴일근로의 예상 지급액을 계산합니다.",
    searchAliases: ["알바", "야간수당", "연장수당", "휴일수당", "초과근무"],
    searchIntents: ["야근하면 얼마를 받는지", "공휴일 근무 수당", "알바 추가 수당"],
    valueGrade: "A",
  },
  {
    id: "youth-future-savings",
    path: "/calculators/youth-future-savings/",
    title: "청년미래적금 계산기",
    category: "금융",
    description: "정부기여금과 금리를 반영한 원금·이자·예상 만기수령액을 구분합니다.",
    searchAliases: ["청년 적금", "정부기여금", "청년 저축", "청년미래저축"],
    searchIntents: ["정부 지원 적금 만기액", "청년 적금 혜택"],
    valueGrade: "A",
  },
  {
    id: "dsr",
    path: "/calculators/dsr/",
    title: "DSR 계산기",
    category: "금융",
    description: "기존·신규 대출 원리금과 일반 DSR·스트레스 DSR을 비교합니다.",
    searchAliases: ["대출 한도", "총부채원리금상환비율", "스트레스 DSR", "부채 비율"],
    searchIntents: ["대출을 더 받을 수 있는지", "소득 대비 원리금", "대출 한도 확인"],
    valueGrade: "A",
    flagship: true,
  },
  {
    id: "work-child-incentive",
    path: "/calculators/work-child-incentive/",
    title: "근로·자녀장려금 계산기",
    category: "급여",
    description: "소득·재산·가구 기준과 법정 구간 산식으로 예상 장려금을 계산합니다.",
    searchAliases: ["근로장려금", "자녀장려금", "장려금", "지원금"],
    searchIntents: ["소득으로 받을 장려금", "자녀가 있으면 받는 지원금"],
    valueGrade: "A",
    flagship: true,
  },
  {
    id: "training-certificate-cost",
    path: "/calculators/training-certificate-cost/",
    title: "국비지원 자격증 취득비용 계산기",
    category: "생활",
    description: "훈련비 본인부담과 시험·교재·부대비용을 합쳐 자격증 취득 예상비용을 계산합니다.",
    searchAliases: ["국비지원", "내일배움카드", "자격증 비용", "훈련비"],
    searchIntents: ["국비지원 후 내가 내는 돈", "자격증 취득 총비용"],
    valueGrade: "B",
  },
] as const satisfies readonly CalculatorRegistryItem[];

export type CalculatorId = (typeof CALCULATOR_REGISTRY)[number]["id"];

