import { ApiError, success } from "../domain/errors";
import type { AdminActor } from "../security/admin";
import { enforceRateLimit } from "../security/rate-limit";
import { hmacHash } from "../security/tokens";
import { text, passwordInput, hashPassword, verifyPassword, assertServices, audit, seedStatements, answerStatement, knowledgeCategory } from "../domain/knowledge";
import { assertIdempotencyKey, assertUuid, parseLimit, readJson } from "../security/validation";
import { verifyTurnstile, type TurnstileCategory } from "../security/turnstile";
import { assertIdempotencyMatch, findIdempotency, requestHash } from "../security/idempotency";
import { VISITOR_QUESTION_CREATE_FIELDS } from "../../../../lib/knowledge/visitor-contract";
import { assertKnowledgeSpamInput, assertKnowledgeAdmission, knowledgeAdmission, knowledgeAdmissionPredicate, expiredKnowledgeGuards } from "../security/knowledge-spam";

type Result = { response: Response; meta: { turnstile: TurnstileCategory; rateLimit: "pass" | "limited" | "not_applied" } };
const meta = (turnstile: TurnstileCategory = "not_required", rateLimit: "pass" | "limited" | "not_applied" = "not_applied") => ({ turnstile, rateLimit });
const now = () => new Date().toISOString();
const result = (requestId: string, data: unknown, status = 200, turnstile: TurnstileCategory = "not_required", rateLimit: "pass" | "limited" | "not_applied" = "not_applied"): Result => ({ response: success(requestId, data, status, { "Cache-Control": "no-store" }), meta: meta(turnstile, rateLimit) });
const serviceRows = async (db: D1Database, id: string) => (await db.prepare("SELECT s.id,s.slug,s.name,s.path FROM knowledge_question_services r JOIN services s ON s.id=r.service_id WHERE r.question_id=?1 AND s.status='active' ORDER BY s.name,s.id").bind(id).all()).results;
const answerRow = async (db: D1Database, id: string) => await db.prepare("SELECT id,body,created_at,updated_at FROM knowledge_answers WHERE question_id=?1").bind(id).first();
const questionPayload = async (db: D1Database, row: Record<string, unknown>) => ({ id: row.id, isAnonymous: Boolean(row.is_anonymous), nickname: row.is_anonymous ? null : row.nickname, title: row.title, body: row.body, category: row.category ?? null, origin: row.origin, status: row.status, createdAt: row.created_at, updatedAt: row.updated_at, passwordConfigured: typeof row.password_hash === "string" && row.password_hash.length > 0, answer: await answerRow(db, String(row.id)), relatedServices: await serviceRows(db, String(row.id)) });
const publicQuestionPayload = async (db: D1Database, row: Record<string, unknown>) => { const payload = await questionPayload(db, row); const publicPayload: Partial<typeof payload> = { ...payload }; delete publicPayload.origin; delete publicPayload.status; delete publicPayload.updatedAt; delete publicPayload.passwordConfigured; return publicPayload; };
const parseQuestion = (raw: Record<string, unknown>, adminSeed = false) => { const allowed: readonly string[] = adminSeed ? VISITOR_QUESTION_CREATE_FIELDS.filter(key => key !== "website") : VISITOR_QUESTION_CREATE_FIELDS; if (Object.keys(raw).some(k => !allowed.includes(k))) throw new ApiError(400, "INVALID_INPUT", "허용되지 않은 필드가 있습니다."); if (!adminSeed) assertKnowledgeSpamInput(raw); const anonymous = adminSeed ? true : raw.isAnonymous === true; if (!adminSeed && typeof raw.isAnonymous !== "boolean") throw new ApiError(400, "INVALID_INPUT", "익명 여부를 확인해 주세요."); const nickname = anonymous ? null : text(raw.nickname, "닉네임", 2, 40); const password = passwordInput(raw.password); const body = text(raw.body, "질문 내용", 1, 4000); const title = raw.title === undefined && adminSeed ? body.slice(0, 80) : text(raw.title, "질문 제목", 1, 120); const serviceIds = raw.serviceIds === undefined ? [] : raw.serviceIds; if (!Array.isArray(serviceIds) || serviceIds.length > 21 || serviceIds.some(id => typeof id !== "string")) throw new ApiError(400, "INVALID_INPUT", "관련 계산기 형식이 올바르지 않습니다."); const unique = [...new Set(serviceIds as string[])]; unique.forEach(assertUuid); return { anonymous, nickname, password, title, body, category: raw.category === undefined ? null : knowledgeCategory(raw.category), serviceIds: unique, token: typeof raw.turnstile_token === "string" ? raw.turnstile_token : "" }; };
const adminMutation = async (db: D1Database, actor: AdminActor, request: Request, target: string, body: unknown) => { const key = assertIdempotencyKey(request.headers.get("Idempotency-Key")); const hash = await requestHash("admin_mutation", target, body); const existing = await findIdempotency(db, "admin_mutation", actor.hash, key); if (existing) { assertIdempotencyMatch(existing, hash); return { key, hash, replay: true }; } return { key, hash, replay: false }; };
const saveIdempotency = (db: D1Database, actor: AdminActor, key: string, hash: string, id: string, at: string) => db.prepare("INSERT INTO knowledge_idempotency_records (operation,owner_token_hash,idempotency_key,request_hash,resource_id,created_at,expires_at) VALUES ('admin_mutation',?1,?2,?3,?4,?5,?6)").bind(actor.hash, key, hash, id, at, new Date(Date.now() + 86400000).toISOString());

export const listKnowledgeQuestions = async (request: Request, env: Env, requestId: string): Promise<Result> => { const u = new URL(request.url), q = u.searchParams.get("query")?.trim(), status = u.searchParams.get("status"), answered = u.searchParams.get("answered"), category = u.searchParams.get("category"), service = u.searchParams.get("service"), limit = parseLimit(u.searchParams.get("limit"), 20, 20), rawPage = u.searchParams.get("page") || "1"; if (!/^\d+$/u.test(rawPage) || Number(rawPage) < 1) throw new ApiError(400, "INVALID_INPUT", "page 값이 올바르지 않습니다."); if (status && !["draft", "published", "hidden"].includes(status)) throw new ApiError(400, "INVALID_INPUT", "status 값이 올바르지 않습니다."); if (answered && !["yes", "no"].includes(answered)) throw new ApiError(400, "INVALID_INPUT", "answered 값이 올바르지 않습니다."); if (category) knowledgeCategory(category); if (service) assertUuid(service); const conditions: string[] = [], values: unknown[] = []; if (status) { conditions.push("q.status=?"); values.push(status); } if (answered === "yes") conditions.push("EXISTS (SELECT 1 FROM knowledge_answers a WHERE a.question_id=q.id)"); if (answered === "no") conditions.push("NOT EXISTS (SELECT 1 FROM knowledge_answers a WHERE a.question_id=q.id)"); if (category) { conditions.push("q.category=?"); values.push(category); } if (service) { conditions.push("EXISTS (SELECT 1 FROM knowledge_question_services s WHERE s.question_id=q.id AND s.service_id=?)"); values.push(service); } if (q) { conditions.push("(instr(lower(q.body), lower(?)) > 0 OR instr(lower(COALESCE(q.nickname,'')), lower(?)) > 0 OR instr(lower(q.title), lower(?)) > 0)"); values.push(q, q, q); } const where = conditions.length ? ` WHERE ${conditions.join(" AND ")}` : "", total = Number((await env.KNOWLEDGE_DB.prepare(`SELECT COUNT(*) total FROM knowledge_questions q${where}`).bind(...values).first<{ total: number }>())?.total || 0), page = Number(rawPage), pages = Math.max(1, Math.ceil(total / limit)), safe = Math.min(page, pages), rows = (await env.KNOWLEDGE_DB.prepare(`SELECT q.* FROM knowledge_questions q${where} ORDER BY q.updated_at DESC,q.id DESC LIMIT ? OFFSET ?`).bind(...values, limit, (safe - 1) * limit).all()).results; return result(requestId, { items: await Promise.all(rows.map(row => questionPayload(env.KNOWLEDGE_DB, row as Record<string, unknown>))), page: safe, page_size: limit, total, total_pages: pages }); };
export const listPublicKnowledgeServices = async (env: Env, requestId: string): Promise<Result> => result(requestId, { items: (await env.KNOWLEDGE_DB.prepare("SELECT id,slug,name,path FROM services WHERE status='active' ORDER BY name ASC").all()).results });
export const listPublicKnowledgeQuestions = async (request: Request, env: Env, requestId: string): Promise<Result> => { const u = new URL(request.url), service = u.searchParams.get("service"), rawQuery = u.searchParams.get("q"), query = rawQuery?.trim() || "", category = u.searchParams.get("category")?.trim() || "", limit = parseLimit(u.searchParams.get("limit"), 10, 10), page = Math.max(1, Number(u.searchParams.get("page") || "1")); if (query.length > 50) throw new ApiError(400, "INVALID_INPUT", "검색어는 50자 이내로 입력해 주세요."); if (service) assertUuid(service); if (category) knowledgeCategory(category); const values: unknown[] = []; let where = " WHERE q.status='published'"; if (service) { where += " AND EXISTS (SELECT 1 FROM knowledge_question_services s WHERE s.question_id=q.id AND s.service_id=?)"; values.push(service); } if (category) { where += " AND q.category=?"; values.push(category); } if (query) { const escaped = query.replace(/[\\%_]/gu, character => `\\${character}`); where += " AND (q.title LIKE ? ESCAPE char(92) OR q.body LIKE ? ESCAPE char(92))"; values.push(`%${escaped}%`, `%${escaped}%`); } const total = Number((await env.KNOWLEDGE_DB.prepare(`SELECT COUNT(*) total FROM knowledge_questions q${where}`).bind(...values).first<{ total: number }>())?.total || 0), totalPages = Math.max(1, Math.ceil(total / limit)), safePage = Math.min(page, totalPages); const rows = (await env.KNOWLEDGE_DB.prepare(`SELECT q.* FROM knowledge_questions q${where} ORDER BY q.created_at DESC,q.id DESC LIMIT ? OFFSET ?`).bind(...values, limit, (safePage - 1) * limit).all()).results; return result(requestId, { items: await Promise.all(rows.map(row => publicQuestionPayload(env.KNOWLEDGE_DB, row as Record<string, unknown>))), page: safePage, page_size: limit, total, total_pages: totalPages }); };
export const getKnowledgeQuestion = async (env: Env, requestId: string, id: string): Promise<Result> => { assertUuid(id); const row = await env.KNOWLEDGE_DB.prepare("SELECT * FROM knowledge_questions WHERE id=?1").bind(id).first<Record<string, unknown>>(); if (!row) throw new ApiError(404, "NOT_FOUND", "지식센터 질문을 찾을 수 없습니다."); return result(requestId, { question: await questionPayload(env.KNOWLEDGE_DB, row) }); };
export const getPublicKnowledgeQuestion = async (env: Env, requestId: string, id: string): Promise<Result> => { assertUuid(id); const row = await env.KNOWLEDGE_DB.prepare("SELECT * FROM knowledge_questions WHERE id=?1 AND status='published'").bind(id).first<Record<string, unknown>>(); if (!row) throw new ApiError(404, "NOT_FOUND", "지식센터 질문을 찾을 수 없습니다."); return result(requestId, { question: await publicQuestionPayload(env.KNOWLEDGE_DB, row) }); };
export const createKnowledgeQuestion = async (request: Request, env: Env, requestId: string): Promise<Result> => {
  const input = parseQuestion(await readJson(request));
  if (!input.token) throw new ApiError(400, "TURNSTILE_REQUIRED", "Turnstile 토큰이 필요합니다.");
  const turnstile = await verifyTurnstile(input.token, env.TURNSTILE_SECRET, env);
  const ip = request.headers.get("CF-Connecting-IP") || "unknown";
  const clientHash = await hmacHash(env.AUTHOR_TOKEN_PEPPER, "client", ip);
  await enforceRateLimit(env.KNOWLEDGE_WRITE_LIMITER, clientHash);
  await assertServices(env.KNOWLEDGE_DB, input.serviceIds);
  const admission = await knowledgeAdmission(env.AUTHOR_TOKEN_PEPPER, ip, input.title, input.body);
  await assertKnowledgeAdmission(env.KNOWLEDGE_DB, admission);
  const id = crypto.randomUUID(), at = now(), hash = await hashPassword(input.password), db = env.KNOWLEDGE_DB;
  const writes = await db.batch([
    expiredKnowledgeGuards(db, admission.time),
    db.prepare(`WITH a AS (SELECT ?1 requester_hash,?2 content_hash,?3 ten_min,?4 hour,?5 minute)
      INSERT INTO knowledge_questions (id,is_anonymous,nickname,password_hash,title,body,origin,status,created_at,updated_at,category)
      SELECT ?6,?7,?8,?9,?10,?11,'user','published',?12,?12,?13 FROM a WHERE ${knowledgeAdmissionPredicate}`)
      .bind(admission.requesterHash, admission.contentHash, admission.time - 600_000, admission.time - 3_600_000, admission.time - 60_000, id, input.anonymous ? 1 : 0, input.nickname, hash, input.title, input.body, at, input.category),
    db.prepare("INSERT INTO knowledge_submission_guards (id,question_id,requester_hash,content_hash,created_at) SELECT ?1,?1,?2,?3,?4 FROM knowledge_questions WHERE id=?1").bind(id, admission.requesterHash, admission.contentHash, admission.time),
    ...input.serviceIds.map(serviceId => db.prepare("INSERT INTO knowledge_question_services (question_id,service_id,created_at) SELECT ?1,?2,?3 FROM knowledge_questions WHERE id=?1").bind(id, serviceId, at)),
  ]);
  if (!writes[1].meta.changes) {
    await assertKnowledgeAdmission(db, admission);
    throw new ApiError(429, "RATE_LIMITED", "잠시 후 다시 시도해 주세요.", 600);
  }
  return result(requestId, { id, status: "published" }, 201, turnstile, "pass");
};
const visitorEditInput = async (request: Request, env: Env, fields: string[]) => {
  const raw = await readJson(request);
  if (Object.keys(raw).some(key => !fields.includes(key))) throw new ApiError(400, "INVALID_INPUT", "허용되지 않은 필드가 있습니다.");
  const password = passwordInput(raw.password);
  const token = typeof raw.turnstile_token === "string" ? raw.turnstile_token : "";
  if (!token) throw new ApiError(400, "TURNSTILE_REQUIRED", "Turnstile 토큰이 필요합니다.");
  const clientHash = await hmacHash(env.AUTHOR_TOKEN_PEPPER, "client", request.headers.get("CF-Connecting-IP") || "unknown");
  if (env.KNOWLEDGE_WRITE_LIMITER) await enforceRateLimit(env.KNOWLEDGE_WRITE_LIMITER, clientHash);
  return { raw, password, token };
};

const authenticatedEditableQuestion = async (db: D1Database, id: string, password: string) => {
  const row = await db.prepare("SELECT password_hash,is_anonymous,status,title FROM knowledge_questions WHERE id=?1")
    .bind(id).first<{ password_hash: string; is_anonymous: number; status: string; title: string }>();
  if (!row || row.status !== "published") throw new ApiError(404, "NOT_FOUND", "지식센터 질문을 찾을 수 없습니다.");
  if (await answerRow(db, id)) throw new ApiError(409, "INVALID_STATE", "공식답변이 등록되어 수정할 수 없습니다.");
  if (!(await verifyPassword(password, row.password_hash))) throw new ApiError(403, "FORBIDDEN", "비밀번호가 일치하지 않습니다.");
  return row;
};

// This check never grants a reusable credential: PATCH independently verifies the current password again.
export const verifyKnowledgeQuestionPassword = async (request: Request, env: Env, requestId: string, id: string): Promise<Result> => {
  assertUuid(id);
  const { password, token } = await visitorEditInput(request, env, ["password", "turnstile_token"]);
  await authenticatedEditableQuestion(env.KNOWLEDGE_DB, id, password);
  const turnstile = await verifyTurnstile(token, env.TURNSTILE_SECRET, env);
  return result(requestId, { verified: true }, 200, turnstile, "pass");
};

export const patchKnowledgeQuestion = async (request: Request, env: Env, requestId: string, id: string): Promise<Result> => {
  assertUuid(id);
  const { raw, password, token } = await visitorEditInput(request, env, ["password", "nickname", "title", "body", "turnstile_token"]);
  const row = await authenticatedEditableQuestion(env.KNOWLEDGE_DB, id, password);
  const turnstile = await verifyTurnstile(token, env.TURNSTILE_SECRET, env);
  const body = text(raw.body, "질문 내용", 1, 4000);
  const title = raw.title === undefined ? row.title : text(raw.title, "질문 제목", 1, 120);
  const nickname = row.is_anonymous ? null : text(raw.nickname, "닉네임", 2, 40);
  // Recheck both the answer lock and the exact verified hash at the write boundary (including an admin password reset race).
  const updated = await env.KNOWLEDGE_DB.prepare("UPDATE knowledge_questions SET nickname=?1,title=?2,body=?3,updated_at=?4 WHERE id=?5 AND status='published' AND password_hash=?6 AND NOT EXISTS (SELECT 1 FROM knowledge_answers WHERE question_id=?5)")
    .bind(nickname, title, body, now(), id, row.password_hash).run();
  if (!updated.meta.changes) throw new ApiError(409, "INVALID_STATE", "질문 상태가 변경되었습니다. 다시 확인해 주세요.");
  return result(requestId, { id, status: "published" }, 200, turnstile, "pass");
};

export const deleteKnowledgeQuestion = async (request: Request, env: Env, requestId: string, id: string): Promise<Result> => {
  assertUuid(id);
  const { password, token } = await visitorEditInput(request, env, ["password", "turnstile_token"]);
  const row = await env.KNOWLEDGE_DB.prepare("SELECT password_hash,origin,status,EXISTS (SELECT 1 FROM knowledge_imports WHERE question_id=knowledge_questions.id) imported FROM knowledge_questions WHERE id=?1")
    .bind(id).first<{ password_hash: string; origin: string; status: string; imported: number }>();
  if (!row || row.status !== "published") throw new ApiError(404, "NOT_FOUND", "지식센터 질문을 찾을 수 없습니다.");
  if (row.origin !== "user") throw new ApiError(403, "FORBIDDEN", "방문자가 등록한 질문만 삭제할 수 있습니다.");
  if (row.imported) throw new ApiError(403, "FORBIDDEN", "가져온 질문은 방문자가 삭제할 수 없습니다.");
  if (await answerRow(env.KNOWLEDGE_DB, id)) throw new ApiError(409, "INVALID_STATE", "공식답변이 등록되어 삭제할 수 없습니다.");
  if (!(await verifyPassword(password, row.password_hash))) throw new ApiError(403, "FORBIDDEN", "비밀번호가 일치하지 않습니다.");
  const turnstile = await verifyTurnstile(token, env.TURNSTILE_SECRET, env);
  // Recheck all mutable authorization conditions at the write boundary.
  const deleted = await env.KNOWLEDGE_DB.prepare("DELETE FROM knowledge_questions WHERE id=?1 AND origin='user' AND status='published' AND password_hash=?2 AND NOT EXISTS (SELECT 1 FROM knowledge_answers WHERE question_id=?1) AND NOT EXISTS (SELECT 1 FROM knowledge_imports WHERE question_id=?1)")
    .bind(id, row.password_hash).run();
  if (!deleted.meta.changes) {
    const current = await env.KNOWLEDGE_DB.prepare("SELECT status FROM knowledge_questions WHERE id=?1").bind(id).first<{ status: string }>();
    if (!current || current.status !== "published") throw new ApiError(404, "NOT_FOUND", "지식센터 질문을 찾을 수 없습니다.");
    if (await answerRow(env.KNOWLEDGE_DB, id)) throw new ApiError(409, "INVALID_STATE", "공식답변이 등록되어 삭제할 수 없습니다.");
    throw new ApiError(409, "INVALID_STATE", "질문 상태가 변경되었습니다. 다시 확인해 주세요.");
  }
  return result(requestId, { id, deleted: true }, 200, turnstile, "pass");
};

export const createAdminKnowledgeQuestion = async (request: Request, env: Env, requestId: string, actor: AdminActor): Promise<Result> => { const raw = await readJson(request); const input = { ...parseQuestion(raw, true), category: knowledgeCategory(raw.category) }; await assertServices(env.KNOWLEDGE_DB, input.serviceIds); const mutation = await adminMutation(env.KNOWLEDGE_DB, actor, request, "knowledge:create", input); if (mutation.replay) return result(requestId, { idempotent_replay: true }); const id = crypto.randomUUID(), at = now(), hash = await hashPassword(input.password); await env.KNOWLEDGE_DB.batch([...seedStatements(env.KNOWLEDGE_DB, actor, input, id, hash, at), saveIdempotency(env.KNOWLEDGE_DB, actor, mutation.key, mutation.hash, id, at)]); return result(requestId, { id, origin: "admin_seed", status: "published" }, 201); };
export const patchAdminKnowledgeQuestion = async (request: Request, env: Env, requestId: string, actor: AdminActor, id: string): Promise<Result> => { assertUuid(id); const raw = await readJson(request); if (Object.keys(raw).some(key => !["body", "title", "category", "serviceIds", "password"].includes(key))) throw new ApiError(400, "INVALID_INPUT", "허용되지 않은 필드가 있습니다."); const body = text(raw.body, "질문 내용", 1, 4000), title = raw.title === undefined ? undefined : text(raw.title, "질문 제목", 1, 120), passwordHash = raw.password === undefined || raw.password === "" ? undefined : await hashPassword(passwordInput(raw.password)), serviceIds = raw.serviceIds === undefined ? undefined : raw.serviceIds; if (serviceIds !== undefined && (!Array.isArray(serviceIds) || serviceIds.some(x => typeof x !== "string"))) throw new ApiError(400, "INVALID_INPUT", "관련 계산기 형식이 올바르지 않습니다."); const ids = serviceIds ? [...new Set(serviceIds as string[])] : undefined; ids?.forEach(assertUuid); if (ids) await assertServices(env.KNOWLEDGE_DB, ids); const row = await env.KNOWLEDGE_DB.prepare("SELECT id,title,category,status FROM knowledge_questions WHERE id=?1").bind(id).first<{id:string;title:string;category:string|null;status:string}>(); if (!row) throw new ApiError(404, "NOT_FOUND", "지식센터 질문을 찾을 수 없습니다."); const category = knowledgeCategory(raw.category === undefined ? row.category : raw.category); const mutation = await adminMutation(env.KNOWLEDGE_DB, actor, request, `knowledge:update:${id}`, raw); if (mutation.replay) return result(requestId, { idempotent_replay: true, status: "published" }); const at = now(), statements: D1PreparedStatement[] = [passwordHash ? env.KNOWLEDGE_DB.prepare("UPDATE knowledge_questions SET title=?1,body=?2,category=?3,password_hash=?4,status='published',updated_at=?5 WHERE id=?6").bind(title ?? row.title, body, category, passwordHash, at, id) : env.KNOWLEDGE_DB.prepare("UPDATE knowledge_questions SET title=?1,body=?2,category=?3,status='published',updated_at=?4 WHERE id=?5").bind(title ?? row.title, body, category, at, id), audit(env.KNOWLEDGE_DB, actor, "knowledge_question_updated", id, at)]; if (row.status !== "published") statements.push(audit(env.KNOWLEDGE_DB, actor, "knowledge_question_published", id, at)); if (ids) statements.push(env.KNOWLEDGE_DB.prepare("DELETE FROM knowledge_question_services WHERE question_id=?1").bind(id), ...ids.map(serviceId => env.KNOWLEDGE_DB.prepare("INSERT INTO knowledge_question_services (question_id,service_id,created_at) VALUES (?1,?2,?3)").bind(id, serviceId, at)), audit(env.KNOWLEDGE_DB, actor, "knowledge_services_updated", id, at)); statements.push(saveIdempotency(env.KNOWLEDGE_DB, actor, mutation.key, mutation.hash, id, at)); await env.KNOWLEDGE_DB.batch(statements); return result(requestId, { id, status: "published" }); };
export const deleteAdminKnowledgeQuestion = async (request: Request, env: Env, requestId: string, actor: AdminActor, id: string): Promise<Result> => { assertUuid(id); const mutation = await adminMutation(env.KNOWLEDGE_DB, actor, request, `knowledge:delete:${id}`, {}); if (mutation.replay) return result(requestId, { id, deleted: true, idempotent_replay: true }); const row = await env.KNOWLEDGE_DB.prepare("SELECT id FROM knowledge_questions WHERE id=?1").bind(id).first(); if (!row) throw new ApiError(404, "NOT_FOUND", "지식센터 질문을 찾을 수 없습니다."); const at = now(); await env.KNOWLEDGE_DB.batch([env.KNOWLEDGE_DB.prepare("DELETE FROM knowledge_imports WHERE question_id=?1").bind(id), env.KNOWLEDGE_DB.prepare("DELETE FROM knowledge_questions WHERE id=?1").bind(id), audit(env.KNOWLEDGE_DB, actor, "knowledge_question_deleted", id, at), saveIdempotency(env.KNOWLEDGE_DB, actor, mutation.key, mutation.hash, id, at)]); return result(requestId, { id, deleted: true }); };
const answerMutation = async (request: Request, env: Env, requestId: string, actor: AdminActor, id: string, update: boolean): Promise<Result> => { assertUuid(id); const raw = await readJson(request), body = text(raw.body, "공식답변", 1, 4000), row = await env.KNOWLEDGE_DB.prepare("SELECT id FROM knowledge_questions WHERE id=?1").bind(id).first(); if (!row) throw new ApiError(404, "NOT_FOUND", "지식센터 질문을 찾을 수 없습니다."); const existing = await answerRow(env.KNOWLEDGE_DB, id); if (!update && existing) throw new ApiError(409, "DUPLICATE_REQUEST", "공식답변이 이미 존재합니다."); if (update && !existing) throw new ApiError(404, "NOT_FOUND", "공식답변을 찾을 수 없습니다."); const mutation = await adminMutation(env.KNOWLEDGE_DB, actor, request, `knowledge:answer:${id}`, raw); if (mutation.replay) return result(requestId, { idempotent_replay: true }); const at = now(), answerId = existing?.id || crypto.randomUUID(); const stmt = update ? env.KNOWLEDGE_DB.prepare("UPDATE knowledge_answers SET body=?1,updated_at=?2 WHERE question_id=?3").bind(body, at, id) : answerStatement(env.KNOWLEDGE_DB, String(answerId), id, body, at); await env.KNOWLEDGE_DB.batch([stmt, audit(env.KNOWLEDGE_DB, actor, update ? "knowledge_answer_updated" : "knowledge_answer_created", id, at), saveIdempotency(env.KNOWLEDGE_DB, actor, mutation.key, mutation.hash, id, at)]); return result(requestId, { id: answerId, question_id: id }); };
export const createAdminKnowledgeAnswer = (request: Request, env: Env, requestId: string, actor: AdminActor, id: string) => answerMutation(request, env, requestId, actor, id, false);
export const patchAdminKnowledgeAnswer = (request: Request, env: Env, requestId: string, actor: AdminActor, id: string) => answerMutation(request, env, requestId, actor, id, true);
const setKnowledgeStatus = async (request: Request, env: Env, requestId: string, actor: AdminActor, id: string, status: "published" | "hidden") => { assertUuid(id); const row = await env.KNOWLEDGE_DB.prepare("SELECT status FROM knowledge_questions WHERE id=?1").bind(id).first<{ status: string }>(); if (!row) throw new ApiError(404, "NOT_FOUND", "지식센터 질문을 찾을 수 없습니다."); const allowed = status === "published" ? ["draft", "hidden"] : ["published", "draft"]; if (!allowed.includes(row.status)) throw new ApiError(409, "INVALID_STATE", "허용되지 않은 상태 전이입니다."); const mutation = await adminMutation(env.KNOWLEDGE_DB, actor, request, `knowledge:${status}:${id}`, {}); if (mutation.replay) return result(requestId, { idempotent_replay: true }); const at = now(); await env.KNOWLEDGE_DB.batch([env.KNOWLEDGE_DB.prepare("UPDATE knowledge_questions SET status=?1,updated_at=?2 WHERE id=?3").bind(status, at, id), audit(env.KNOWLEDGE_DB, actor, status === "published" ? "knowledge_question_published" : "knowledge_question_hidden", id, at), saveIdempotency(env.KNOWLEDGE_DB, actor, mutation.key, mutation.hash, id, at)]); return result(requestId, { id, status }); };
export const publishAdminKnowledgeQuestion = (request: Request, env: Env, requestId: string, actor: AdminActor, id: string) => setKnowledgeStatus(request, env, requestId, actor, id, "published");
export const hideAdminKnowledgeQuestion = (request: Request, env: Env, requestId: string, actor: AdminActor, id: string) => setKnowledgeStatus(request, env, requestId, actor, id, "hidden");
