import { housingAcquisitionTaxFaqs, housingAcquisitionTaxSources } from "./housingAcquisitionTaxContentData";
import styles from "./SellerMarginContent.module.css";

export function HousingAcquisitionTaxContent() {
  return <div className={styles.content}>
    <section className={styles.section} aria-labelledby="housing-tax-scope"><div className={styles.sectionHeading}><h2 id="housing-tax-scope">계산 범위와 해석</h2><p>개인 명의 국내 주택을 정상 유상으로 취득하는 경우에 한정한 참고 계산입니다.</p></div><div className={styles.interpretationGrid}><article className={styles.infoCard}><h3>과세표준</h3><p>입력한 취득가액을 과세표준으로 사용합니다.</p></article><article className={styles.infoCard}><h3>주택 수·지역</h3><p>취득 전 주택 수와 취득일 기준 조정대상지역 여부로 중과세율을 나눕니다.</p></article><article className={styles.infoCard}><h3>전용 85㎡ 초과</h3><p>농어촌특별세 여부와 세율을 함께 반영합니다.</p></article></div></section>
    <section className={styles.section} aria-labelledby="housing-tax-rules"><div className={styles.sectionHeading}><h2 id="housing-tax-rules">적용 세율과 계산식</h2><p>지방세법 제11조·제13조의2 및 서울시 ETAX의 주택 취득세 모의계산 안내를 2026년 8월 27일 기준으로 확인했습니다.</p></div><dl className={styles.formulaList}><div><dt>기본세율</dt><dd>6억원 이하 1%, 6억원 초과 9억원 이하 산식세율, 9억원 초과 3%</dd></div><div><dt>중과세율</dt><dd>입력한 주택 수와 조정대상지역에 따라 8% 또는 12%</dd></div><div><dt>지방교육세</dt><dd>기본세율은 취득세율의 10%, 중과 구간은 0.4%</dd></div><div><dt>농어촌특별세</dt><dd>전용 85㎡ 초과일 때 기본 0.2%, 중과 구간 0.6% 또는 1%</dd></div></dl><p className={styles.roundingNote}>6억 초과 9억원 이하의 취득세율은 법정 산식에 따라 소수점 넷째 자리까지 반올림하고, 화면의 각 세목 금액은 원 미만을 버림해 참고값으로 표시합니다.</p></section>
    <section className={styles.section} aria-labelledby="housing-tax-exclusions"><div className={styles.sectionHeading}><h2 id="housing-tax-exclusions">자동 반영하지 않는 항목</h2><p>필요한 사실관계가 더 필요한 예외·감면은 0원 또는 미적용으로 표시합니다.</p></div><ul className={styles.exclusionList}>{["생애최초 취득세 감면", "일시적 2주택 및 중과 제외", "공동취득·지분 취득", "상속·증여·부담부증여", "분양권·입주권·주택 외 부동산", "비도시지역의 면적 예외", "지방자치단체별 감면과 가산세"].map((item) => <li key={item}>{item}</li>)}</ul></section>
    <section className={styles.section} aria-labelledby="housing-tax-sources"><div className={styles.sectionHeading}><h2 id="housing-tax-sources">공식 출처</h2><p>법령·행정기관 안내의 현재 문구를 기준으로 확인했습니다.</p></div><ul className={styles.sourceList}>{housingAcquisitionTaxSources.map((source) => <li key={source.href}><div><strong>{source.organization} · {source.title}</strong><span>{source.criterion}</span></div><a href={source.href} target="_blank" rel="noopener noreferrer">확인하기</a></li>)}</ul></section>
    <section className={styles.section} aria-labelledby="housing-tax-related"><div className={styles.sectionHeading}><h2 id="housing-tax-related">관련 계산기</h2></div><div className={styles.relatedGrid}><a className={`${styles.relatedCard} ${styles.relatedLink}`} href="/calculators/brokerage-fee/"><h3>부동산 중개보수 계산기</h3><p>취득세와 별도로 중개보수 예상액을 확인합니다.</p></a><a className={`${styles.relatedCard} ${styles.relatedLink}`} href="/calculators/loan/"><h3>대출 이자 계산기</h3><p>주택자금 대출의 상환 부담을 별도로 계산합니다.</p></a><a className={`${styles.relatedCard} ${styles.relatedLink}`} href="/calculators/"><h3>전체 계산기</h3><p>공개 계산기 목록을 확인합니다.</p></a></div></section>
    <section className={styles.section} aria-labelledby="housing-tax-faq"><div className={styles.sectionHeading}><h2 id="housing-tax-faq">자주 묻는 질문</h2></div><div className={styles.faqList}>{housingAcquisitionTaxFaqs.map(({ question, answer }) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>
    <aside className={styles.disclaimer} aria-label="계산 결과 안내">이 계산기는 신고 전 검토를 돕는 참고용입니다. 실제 과세표준, 주택 수, 지역 지정, 감면 및 세액은 취득일 기준의 관할 지방자치단체 안내와 신고서로 확인하세요. 중개보수, 국민주택채권, 등기·법무 비용은 포함하지 않습니다.</aside>
  </div>;
}
