"use client";
import { type FormEvent, useState } from "react";
import { calculateActualConversionRate, calculateDepositToRent, calculateRentToDeposit, getEffectiveStatutoryCeiling, RENT_CONVERSION_POLICY, validateAmount, validateRate, type RentConversionResult } from "@/lib/calculators/rent-conversion-rate";
import styles from "./RentConversionRateCalculator.module.css";

type Mode = "deposit-to-rent" | "rent-to-deposit" | "actual-rate";
const money = new Intl.NumberFormat("ko-KR", { maximumFractionDigits: 0 });
const won = (value: number) => `${money.format(value)}원`;
const rate = (value: number) => `${Number(value.toFixed(4))}%`;
const formatInput = (value: string) => /^\d+$/.test(value.replaceAll(",", "")) ? value.replaceAll(",", "").replace(/\B(?=(\d{3})+(?!\d))/g, ",") : value;

export function RentConversionRateCalculator() {
  const [mode, setMode] = useState<Mode>("deposit-to-rent"); const [first, setFirst] = useState(""); const [second, setSecond] = useState(""); const [inputRate, setInputRate] = useState("4.75"); const [result, setResult] = useState<RentConversionResult | null>(null); const [error, setError] = useState<string | null>(null);
  const firstLabel = mode === "rent-to-deposit" ? "월세 증가액" : "감소한 보증금";
  const hasRate = mode !== "actual-rate";
  function switchMode(next: Mode) { setMode(next); setFirst(""); setSecond(""); setResult(null); setError(null); }
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const firstAmount = Number(first.replaceAll(",", "")); const secondAmount = Number(second.replaceAll(",", "")); const annualRate = Number(inputRate);
    const firstError = validateAmount(firstAmount, firstLabel); const secondError = mode === "actual-rate" ? validateAmount(secondAmount, "월세 증가액") : null; const rateError = hasRate ? validateRate(annualRate) : null; const problem = firstError ?? secondError ?? rateError; if (problem) { setError(problem.message); setResult(null); return; }
    setResult(mode === "deposit-to-rent" ? calculateDepositToRent(firstAmount, annualRate) : mode === "rent-to-deposit" ? calculateRentToDeposit(firstAmount, annualRate) : calculateActualConversionRate(firstAmount, secondAmount)); setError(null);
  }
  function reset() { setFirst(""); setSecond(""); setInputRate("4.75"); setResult(null); setError(null); }
  const primary = result && (mode === "deposit-to-rent" ? result.monthlyAmount : mode === "rent-to-deposit" ? result.monthlyAmount : result.appliedRate);
  return <div className={styles.calculator}><form className={styles.card} onSubmit={submit} noValidate><p className={styles.step}>01 · 계산 조건</p><h2>보증금과 월세를 환산해 보세요</h2><div className={styles.modes} role="group" aria-label="계산 모드">{([['deposit-to-rent','보증금 → 월세'],['rent-to-deposit','월세 → 보증금'],['actual-rate','실제 전환율 확인']] as const).map(([key,label]) => <button type="button" key={key} aria-pressed={mode===key} className={mode===key?styles.active:""} onClick={() => switchMode(key)}>{label}</button>)}</div><label htmlFor="rent-first">{firstLabel}</label><div className={styles.input}><input id="rent-first" aria-label={firstLabel} inputMode="numeric" value={first} onChange={(event)=>setFirst(formatInput(event.target.value))}/><span>원</span></div>{mode === "actual-rate" && <><label htmlFor="rent-second">월세 증가액</label><div className={styles.input}><input id="rent-second" aria-label="월세 증가액" inputMode="numeric" value={second} onChange={(event)=>setSecond(formatInput(event.target.value))}/><span>원</span></div></>}{hasRate && <><label htmlFor="rent-rate">적용 전환율</label><div className={styles.input}><input id="rent-rate" aria-label="적용 전환율" inputMode="decimal" value={inputRate} onChange={(event)=>setInputRate(event.target.value)}/><span>%</span></div></>}<p className={styles.policy}>한국은행 기준금리 {RENT_CONVERSION_POLICY.bokBaseRate}% + {RENT_CONVERSION_POLICY.statutoryAdditiveRate}%p · 현재 법정 참고 상한 {getEffectiveStatutoryCeiling()}%</p>{error && <p className={styles.error} role="alert">{error}</p>}<div className={styles.actions}><button type="submit">계산하기</button><button type="button" onClick={reset}>초기화</button></div></form><section className={styles.card} aria-live="polite" aria-label="전환율 계산 결과">{!result?<div className={styles.empty}><h2>전환 조건을 입력해 주세요</h2><p>현재 법정 참고 상한과 함께 예상 환산 결과를 확인합니다.</p></div>:<><p className={styles.step}>02 · 예상 결과</p><h2>{mode === "deposit-to-rent" ? "월세 증가액" : mode === "rent-to-deposit" ? "환산 보증금" : "실제 연 전환율"}</h2><strong className={styles.primary}>{typeof primary === "number" ? (mode === "actual-rate" ? rate(primary) : won(primary)) : ""}</strong><dl><div><dt>연 환산 금액</dt><dd>{won(result.annualAmount)}</dd></div>{mode !== "actual-rate" && <div><dt>적용 전환율</dt><dd>{rate(result.appliedRate)}</dd></div>}<div><dt>현재 법정 참고 상한</dt><dd>{rate(result.effectiveStatutoryCeiling)}</dd></div>{mode === "actual-rate" && <div><dt>상한과의 차이</dt><dd>{rate(Math.abs(result.rateDifference))}p {result.comparison === "above" ? "높음" : result.comparison === "below" ? "낮음" : "같음"}</dd></div>}</dl><p className={styles.note}>법 적용 대상과 계약의 적법성을 최종 판정하는 결과는 아닙니다.</p></>}</section></div>;
}
