"use client";
import { type FormEvent, useState } from "react";
import { calculateVehicleAcquisitionTaxFromUnknown, vehicleTypes, type AcquisitionMode, type EcoType, type VehicleTaxResult, type VehicleType } from "@/lib/calculators/vehicle-acquisition-tax";
import styles from "./VehicleAcquisitionTaxCalculator.module.css";
const money = new Intl.NumberFormat("ko-KR"); const won = (v: number) => `${money.format(v)}원`; const percent = (v: number) => `${Math.round(v * 100)}%`;
const reliefNames = { none: "적용 없음", electric: "전기자동차 감면", hydrogen: "수소전기자동차 감면", lightPassenger: "경형 승용자동차 감면", lightOther: "경형 승합·화물차 면제" } as const;
export function VehicleAcquisitionTaxCalculator() {
  const [mode, setMode] = useState<AcquisitionMode>("new"); const [vehicleType, setVehicleType] = useState<VehicleType>("passenger"); const [ecoType, setEcoType] = useState<EcoType>("none"); const [price, setPrice] = useState(""); const [standard, setStandard] = useState(""); const [result, setResult] = useState<VehicleTaxResult | null>(null); const [error, setError] = useState("");
  const format = (value: string) => /^\d*$/.test(value.replaceAll(",", "")) ? value.replaceAll(",", "").replace(/\B(?=(\d{3})+(?!\d))/g, ",") : value;
  function submit(event: FormEvent) { event.preventDefault(); const response = calculateVehicleAcquisitionTaxFromUnknown({ acquisitionMode: mode, vehicleType, ecoType, taxableBaseInput: Number(price.replaceAll(",", "")), standardValue: mode === "used" ? Number(standard.replaceAll(",", "")) : undefined }); if (!response.success) { setError(response.errors[0].message); setResult(null); return; } setError(""); setResult(response.data); }
  function reset() { setMode("new"); setVehicleType("passenger"); setEcoType("none"); setPrice(""); setStandard(""); setError(""); setResult(null); }
  return <div className={styles.calculator}><form className={styles.card} onSubmit={submit} noValidate><p className={styles.step}>01 · 차량 조건</p><h2>차량 취득 조건을 입력하세요</h2><label>취득 방식<select aria-label="취득 방식" value={mode} onChange={e=>{ setMode(e.target.value as AcquisitionMode); setResult(null); }}><option value="new">신차 또는 일반 유상취득</option><option value="used">중고차 유상취득</option></select></label><label>차량 유형<select aria-label="차량 유형" value={vehicleType} onChange={e=>{ setVehicleType(e.target.value as VehicleType); setResult(null); }}>{vehicleTypes.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>친환경 유형<select aria-label="친환경 유형" value={ecoType} onChange={e=>{setEcoType(e.target.value as EcoType);setResult(null);}}><option value="none">해당 없음</option><option value="electric">전기차</option><option value="hydrogen">수소전기차</option></select></label><label htmlFor="vehicle-price">{mode === "used" ? "실제 취득가격" : "취득세 과세표준액"}</label><div className={styles.input}><input id="vehicle-price" aria-label={mode === "used" ? "실제 취득가격" : "취득세 과세표준액"} inputMode="numeric" value={price} onChange={e=>setPrice(format(e.target.value))}/><span>원</span></div>{mode === "new" ? <p className={styles.hint}>차량을 취득하기 위해 실제 지급한 금액 등을 기준으로 하며, 정확한 신고 과세표준은 등록 서류를 확인하세요.</p> : <><label htmlFor="vehicle-standard">차량 시가표준액</label><div className={styles.input}><input id="vehicle-standard" aria-label="차량 시가표준액" inputMode="numeric" value={standard} onChange={e=>setStandard(format(e.target.value))}/><span>원</span></div><p className={styles.hint}>중고차는 실제 취득가격과 시가표준액 중 높은 금액을 과세표준으로 계산합니다.</p></>}<p className={styles.hint}>감면이 둘 이상 가능한 경우에는 합산하지 않고 가장 큰 하나만 예상 반영합니다.</p>{error && <p className={styles.error} role="alert">{error}</p>}<div className={styles.actions}><button type="submit">예상 취득세 계산</button><button type="button" onClick={reset}>초기화</button></div></form><section className={styles.card} aria-live="polite" aria-label="자동차 취득세 계산 결과">{!result ? <div className={styles.empty}><h2>입력 조건 기준 예상 취득세</h2><p>차량 유형, 취득 방식, 과세표준을 입력해 주세요.</p></div> : <><p className={styles.step}>02 · 예상 결과</p><h2>예상 최종 취득세</h2><strong className={styles.primary}>{won(result.finalTax)}</strong><p className={styles.hint}>{mode === "new" ? "입력한 취득가격을 과세표준으로 가정한 예상치" : "입력한 중고차 조건 기준 예상치"}</p><dl>{mode === "used" && <><div><dt>입력 취득가격</dt><dd>{won(result.actualPrice!)}</dd></div><div><dt>입력 시가표준액</dt><dd>{won(result.standardValue!)}</dd></div></>}<div><dt>적용 과세표준</dt><dd>{won(result.taxableBase)}</dd></div><div><dt>적용 세율</dt><dd>{percent(result.rate)}</dd></div><div><dt>산출 취득세</dt><dd>{won(result.grossTax)}</dd></div><div><dt>적용 감면</dt><dd>{reliefNames[result.reliefType]}</dd></div><div><dt>감면액</dt><dd>{won(result.reliefAmount)}</dd></div></dl><p className={styles.hint}>실제 신고·감면 대상 여부, 차량 고시 대상 및 계약 조건에 따라 달라질 수 있습니다.</p></>}</section></div>;
}
